title: Zer0's Blog : The Never Ending Journey.
author: StudentZer0
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The new blogging portal for all things learning, writteng by struden Zer0.

# social links
twitter_username: Zer0 # DO NOT include the @ character, or else the build will fail!
github_username:  StdentZer0 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
